### ISSUE TITLE
Support DEFAULT Target type per Name/Version

### ISSUE THREAD

**Issue by aslakknutsen** [arquillian/arquillian-container-chameleon#35]
We could allow Target Type to be optional for an even quicker experience. The Container configuration should have an option to define which adapter type is the default.

From userview:

```xml
   <property name="chameleonTarget">wildfly:9.0.0.Final</property>
```

From configuration view:

```yaml
- name: WildFly
  adapters:
   - type: embedded
   - type: remote
   - type: managed
  defaultType: managed
```

When no Target type is provided by user, Chameleon should refer to Container configuration to decide which adapter should be loaded. Preferably the adapter that require no configuration and can be fully automated, e.g. managed or embedded.
